import {
  AuthorFields,
  SectorSpecialismFields,
  DifferencePillarFields,
  ProcessStepFields,
  InsightArticleFields,
  SiteSettingsFields,
  HeroSectionData,
  AboutPartnerSectionData,
  ContactFooterSectionData,
  ModularPageData,
} from './types';

export const fallbackSiteSettings: SiteSettingsFields = {
  siteName: 'MG Headhunting',
  tagline: 'Building Products',
  primaryEmail: 'mgoldsmith@mgheadhunting.co.uk',
  phone: '07570 740490',
  headquarters: 'London & Home Counties, United Kingdom',
  linkedinUrl: 'https://www.linkedin.com/in/markgoldsmith2/',
  icoRegistrationNumber: "UK GDPR Compliant • Registered with Information Commissioner's Office (ICO) • Strict Non-Disclosure Assured",
  metaTitleDefault: 'MG Headhunting (MGH) | Retained Executive Search for Building Products & Construction',
  metaDescriptionDefault: 'Boutique retained executive search delivering Board, Managing Director, and C-Suite appointments across the UK and European Building Products and Built Environment sectors.',
  navLinks: [
    { label: 'Specialisms', href: '#specialisms' },
    { label: 'The Difference', href: '#difference' },
    { label: 'Search Process', href: '#process' },
    { label: 'Market Intelligence', href: '/insights' },
    { label: 'FAQ', href: '/faq' },
  ],
  footerSpecialisms: [
    'Managing Directors & CEOs',
    'Commercial & Sales Directors',
    'Operations & Plant Heads',
    'Technical & R&D Directors',
    'Finance & Corporate Development',
    'Sustainability & ESG Leadership',
  ],
  footerSubSectors: [
    'Heavy Materials, Concrete & Aggregates',
    'Building Envelope, Façades & Glazing',
    'HVAC, Mechanical & Building Services',
    'Structural Timber & Offsite MMC',
    'Builders Merchant & Trade Distribution',
    'Roofing, Cladding & Waterproofing',
  ],
  copyrightText: '© 2026 MG Headhunting Ltd. All rights reserved.',
};

export const fallbackHeroData: HeroSectionData = {
  badgeOverline: 'Retained Executive Search',
  badgeCategory: 'Building Products & Construction',
  headline: 'Board, Managing Director & C-Suite Appointments for the',
  highlightedPhrase: 'Built Environment',
  subtitle: 'MG Headhunting (MGH) delivers precision-engineered executive search for manufacturers, distributors, and private equity investors across the Building Products sector. Partner-led, rigorously assessed, and strictly confidential.',
  keyValues: [
    'Zero Transactional Recruitment',
    '100% Partner Execution',
    'Deep Sector Discretion',
  ],
  ctaPrimaryText: 'Start the Conversation',
  ctaSecondaryText: 'View Sector Specialisms',
  complianceNotice: 'Operating under UK Executive Search Code of Conduct & Strict Data Protection protocols.',
  partnerName: 'Mark Goldsmith',
  partnerTitle: 'Managing Director & Lead Search Partner',
  partnerBio: 'Specialist in board appointments, P&L leaders, and commercial turnarounds across heavy building materials, façades, HVAC, and timber systems.',
  metricPlacements: '200+',
  metricTenure: '20+ Yrs',
  metricRetention: '96%',
  metricCoverage: 'UK & EU',
};

export const fallbackSpecialisms: SectorSpecialismFields[] = [
  {
    category: 'EXECUTIVE',
    title: 'Managing Directors & CEOs',
    subtitle: 'General Management & Executive Leadership',
    description: 'Retained search for full P&L owners responsible for driving EBITDA expansion, navigating private equity ownership, organizational restructuring, or scale-up manufacturing.',
    sampleRoles: ['Managing Director', 'Chief Executive Officer', 'Divisional President', 'General Manager', 'Operating Partner'],
    keyClients: 'PE Portfolio Companies, Global Building Materials PLCs',
    order: 1,
  },
  {
    category: 'COMMERCIAL',
    title: 'Commercial & Sales Directors',
    subtitle: 'Specification & Trade Distribution',
    description: 'High-performing commercial leaders experienced with architectural specification, main contractor frameworks, builders merchant distribution networks, and digital pricing models.',
    sampleRoles: ['Chief Commercial Officer', 'Commercial Director', 'Sales Director UK & Ireland', 'Head of Specification', 'National Merchant Controller'],
    keyClients: 'Façade Systems, Heavy Materials, Insulation & Drylining',
    order: 2,
  },
  {
    category: 'OPERATIONS',
    title: 'Operations & Supply Chain',
    subtitle: 'Manufacturing Excellence & Multi-Site Logistics',
    description: 'Engineering-led leaders with deep command of modern manufacturing techniques, Lean Six Sigma, capital plant investment, health & safety culture, and resilient supply chains.',
    sampleRoles: ['Chief Operating Officer', 'Operations Director', 'Plant / Site Director', 'Supply Chain Director', 'Continuous Improvement Head'],
    keyClients: 'Precast Concrete, Glass & Glazing, Brick & Ceramic Plants',
    order: 3,
  },
  {
    category: 'TECHNICAL',
    title: 'Technical, R&D & Compliance',
    subtitle: 'Building Safety Act & Product Engineering',
    description: 'Crucial appointments safeguarding technical integrity, fire safety conformity, Building Safety Act 2022 adherence, thermal acoustics, and Modern Methods of Construction (MMC).',
    sampleRoles: ['Technical Director', 'Head of Product Development', 'Certification & Standards Director', 'Chief Engineer', 'Quality Director'],
    keyClients: 'Cladding & Roofing, Structural Timber, Fire Protection Systems',
    order: 4,
  },
  {
    category: 'EXECUTIVE',
    title: 'Finance & Corporate Development',
    subtitle: 'CFOs & Transaction Specialists',
    description: 'Strategically minded finance directors capable of leading debt refinancing, buy-and-build M&A integrations, supply-chain cost containment, and PE value-creation plans.',
    sampleRoles: ['Chief Financial Officer', 'Finance Director', 'Head of Corporate Development', 'M&A Director', 'Financial Controller'],
    keyClients: 'Building Merchants, Fabricators, Distribution Groups',
    order: 5,
  },
  {
    category: 'TECHNICAL',
    title: 'Sustainability & ESG Leadership',
    subtitle: 'Decarbonization & Circular Materials',
    description: 'Executive drivers of Scope 1-3 carbon reduction, Environmental Product Declarations (EPDs), embodied carbon minimization, and green building product accreditations.',
    sampleRoles: ['Head of Sustainability', 'ESG Director', 'Circular Economy Lead', 'Carbon Transition Strategist'],
    keyClients: 'Cement, Low-Carbon Concrete, Timber Systems',
    order: 6,
  },
];

export const fallbackSubDisciplines = [
  'Heavy Materials & Aggregates',
  'Curtain Walling & Glazing',
  'Structural Timber & Engineered Wood',
  'Offsite & Modular Manufacturing',
  'HVAC, M&E and Pumps',
  'Drylining, Plaster & Insulation',
  'Builders Merchants & Distribution',
  'Roofing, Waterproofing & Cladding',
];

export const fallbackDifferencePillars: DifferencePillarFields[] = [
  {
    title: 'Exclusively Retained Rigour',
    highlight: 'Dedicated Mandates Over Transactional Volume',
    description: 'We do not run high-volume contingent CV races. Every search is a fully retained partnership where we commit our full operational capacity until the ideal executive is placed and integrated.',
    retainedAdvantage: 'Exhaustive 100% market sweep of passive talent with verified track records.',
    contingentFlaw: 'Speed-focused CV spamming of active job seekers already in circulation.',
    iconIdentifier: 'target',
    order: 1,
  },
  {
    title: 'Direct Partner Accountability',
    highlight: 'Zero Junior Consultant Delegation',
    description: 'In traditional search firms, senior partners win the mandate and hand execution to junior researchers. At MGH, Mark Goldsmith personally maps the market, conducts candidate interviews, and leads board negotiations.',
    retainedAdvantage: 'Direct peer-to-peer discussions between C-suite candidates and a seasoned search leader.',
    contingentFlaw: 'Junior recruiters failing to understand technical nuances and boardroom dynamics.',
    iconIdentifier: 'userCheck',
    order: 2,
  },
  {
    title: 'Architectural Blueprint Process',
    highlight: 'Systematic 5-Stage Assessment Protocol',
    description: 'Every candidate undergoes structured competency evaluation, cultural calibration, referencing against previous board peers, and deep commercial validation before presentation.',
    retainedAdvantage: 'Detailed 360° candidate briefing dossiers with verified metrics and leadership impact.',
    contingentFlaw: 'Unvetted CV forwards relying on superficial candidate self-declarations.',
    iconIdentifier: 'compass',
    order: 3,
  },
  {
    title: 'Restricted Covenant Discretion',
    highlight: 'Strict Confidentiality & PE Alignment',
    description: 'We safeguard corporate strategy, sensitive leadership transitions, and competitive positioning under strict non-disclosure, ensuring your brand equity is protected at every touchpoint.',
    retainedAdvantage: 'Discrete approach protocol protecting strategic market intentions and executive reputations.',
    contingentFlaw: 'Public job board advertisements exposing sensitive company restructuring.',
    iconIdentifier: 'shieldCheck',
    order: 4,
  },
];

export const fallbackProcessSteps: ProcessStepFields[] = [
  {
    stepNumber: '01',
    phaseName: 'Calibration',
    title: 'Briefing & Strategic Calibration',
    timeline: 'Week 1',
    description: 'Comprehensive discovery with Board / PE stakeholders to establish operational metrics, cultural leadership requirements, and exact compensation structures.',
    deliverable: 'Role Specification & Search Strategy Dossier',
    order: 1,
  },
  {
    stepNumber: '02',
    phaseName: 'Mapping',
    title: 'Deep Market Mapping & Intelligence',
    timeline: 'Weeks 2–3',
    description: 'Exhaustive research of direct and adjacent competitors across the Building Products ecosystem to identify high-performing passive executives.',
    deliverable: 'Longlist Market Map (~30–50 targets)',
    order: 2,
  },
  {
    stepNumber: '03',
    phaseName: 'Assessment',
    title: 'Confidential Approach & Evaluation',
    timeline: 'Weeks 4–5',
    description: 'Direct partner-led outreach to pre-qualified candidates. In-depth competency interviews, commercial track-record verification, and leadership style assessment.',
    deliverable: 'Calibrated Shortlist & Detailed Candidate Profiles',
    order: 3,
  },
  {
    stepNumber: '04',
    phaseName: 'Presentation',
    title: 'Board Presentation & Negotiation',
    timeline: 'Weeks 6–7',
    description: 'Structured client-candidate interviews, psychometric appraisal alignment, references from previous board peers, and nuanced remuneration structuring.',
    deliverable: 'Shortlist Presentation & Offer Structuring',
    order: 4,
  },
  {
    stepNumber: '05',
    phaseName: 'Integration',
    title: 'Executive Onboarding & 12M Assurance',
    timeline: 'Months 1–12',
    description: 'Active onboarding support during resignation/notice periods, 30/60/90-day progress check-ins with client and appointee, backed by a 12-month placement warranty.',
    deliverable: '100-Day Review & Placement Assurance',
    order: 5,
  },
];

export const fallbackInsightArticles: InsightArticleFields[] = [
  {
    title: 'Case Study: £180M Building Envelope Manufacturer – Managing Director Turnaround',
    slug: 'case-study-building-envelope-managing-director',
    category: 'CASE STUDY',
    publishedDate: 'September 2026',
    readTime: '4 min read',
    excerpt: 'How MGH executed a confidential, partner-led search to appoint a Managing Director capable of restructuring operations and restoring EBITDA margins under private equity ownership.',
    keyTakeaways: [
      'Confidential market sweep delivered 32 pre-qualified passive candidates in 3 weeks',
      'Final appointee secured from a tier-1 European competitor with zero market disruption',
      'Operational turnaround achieved 18% EBITDA recovery within 14 months of appointment',
    ],
    coverImage: {
      sys: { id: 'asset-cover-case-study-1' },
      fields: {
        title: 'Architectural Glazing & Commercial Facade',
        file: {
          url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?q=80&w=1600&auto=format&fit=crop',
        },
      },
    },
    coverImageAlt: 'Architectural glazing installation demonstrating executive turnaround leadership in building envelope manufacturing',
    isFeatured: true,
    author: {
      fields: {
        name: 'Mark Goldsmith',
        roleTitle: 'Managing Director, MGH',
      },
    },
  },
  {
    title: 'Case Study: PE-Backed Trade Merchant Group – Group Commercial Director Placement',
    slug: 'case-study-merchant-group-commercial-director',
    category: 'CASE STUDY',
    publishedDate: 'August 2026',
    readTime: '5 min read',
    excerpt: 'Consolidating six regional merchant acquisitions into a unified national distribution group through the strategic appointment of a high-impact Group Commercial Director.',
    keyTakeaways: [
      'Unanimous board approval of calibrated 4-candidate shortlist within 5 weeks',
      'Strategic harmonisation of supplier rebates and trade pricing architecture',
      'Placement secured with full 12-month post-placement warranty and retention success',
    ],
    coverImage: {
      sys: { id: 'asset-cover-case-study-2' },
      fields: {
        title: 'High-Volume Distribution Centre Logistics',
        file: {
          url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1600&auto=format&fit=crop',
        },
      },
    },
    coverImageAlt: 'Modern high-volume trade distribution and building supplies logistics centre',
    isFeatured: false,
    author: {
      fields: {
        name: 'Mark Goldsmith',
        roleTitle: 'Managing Director, MGH',
      },
    },
  },
  {
    title: 'C-Suite Remuneration Benchmarks in UK Building Materials: Private Equity vs PLC',
    slug: 'c-suite-remuneration-benchmarks-building-materials',
    category: 'EXECUTIVE COMPENSATION',
    publishedDate: 'August 2026',
    readTime: '6 min read',
    excerpt: 'An analysis of base salary trends, LTIP structuring, and co-investment models for Managing Directors and CFOs across European building product manufacturing.',
    keyTakeaways: [
      'PE-backed portfolio MDs seeing equity sweat value outpace base salary expansion',
      'Commercial leadership packages shifting toward EBITDA-linked milestone bonuses',
      'Co-investment requirements solidifying alignment between sponsor funds and incoming executive teams',
    ],
    coverImage: {
      sys: { id: 'asset-cover-c-suite-remuneration' },
      fields: {
        title: 'Executive Boardroom & High-Rise Architecture',
        file: {
          url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1600&auto=format&fit=crop',
        },
      },
    },
    coverImageAlt: 'Executive boardroom and high-rise glass architecture reflecting corporate governance and executive compensation',
    isFeatured: true,
    author: {
      fields: {
        name: 'Mark Goldsmith',
        roleTitle: 'Managing Director, MGH',
      },
    },
  },
  {
    title: 'The Building Safety Act 2022 and the Acute Shortage of Technical Directors',
    slug: 'building-safety-act-technical-director-shortage',
    category: 'REGULATORY & COMPLIANCE',
    publishedDate: 'July 2026',
    readTime: '5 min read',
    excerpt: 'How stricter compliance, Golden Thread documentation, and heightened personal liability have elevated the strategic importance and salary premiums of Technical & Compliance Directors.',
    keyTakeaways: [
      'Demand for chartered facade and fire safety engineers in board roles up 42%',
      'Cross-sector recruitment from aerospace and defense entering high-spec cladding',
      'Gateway 2 and Gateway 3 requirements enforcing personal board liability and documentation integrity',
    ],
    coverImage: {
      sys: { id: 'asset-cover-building-safety-act' },
      fields: {
        title: 'Modern Facade & Engineering Envelope',
        file: {
          url: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?q=80&w=1600&auto=format&fit=crop',
        },
      },
    },
    coverImageAlt: 'Precision engineered architectural building facade demonstrating Building Safety Act technical compliance',
    isFeatured: true,
    author: {
      fields: {
        name: 'MGH Research Desk',
        roleTitle: 'Industry Advisory Group',
      },
    },
  },
  {
    title: 'Consolidation in Merchant Distribution: Appointing Leaders for Buy-and-Build Integrations',
    slug: 'consolidation-merchant-distribution-leadership',
    category: 'M&A & EXPANSION',
    publishedDate: 'June 2026',
    readTime: '7 min read',
    excerpt: 'Why traditional merchant networks require a new profile of Commercial Director capable of uniting fragmented regional acquisitions under centralized digital pricing engines.',
    keyTakeaways: [
      'Omnichannel merchant leaders commanding significant premium over branch-only profiles',
      'Integration velocity directly correlates with pre-existing supplier framework tenure',
      'Centralized rebate optimization and ERP harmonization separating successful PE rollups from stalled integrations',
    ],
    coverImage: {
      sys: { id: 'asset-cover-merchant-distribution' },
      fields: {
        title: 'Modern Distribution Logistics Architecture',
        file: {
          url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1600&auto=format&fit=crop',
        },
      },
    },
    coverImageAlt: 'High-volume commercial distribution and building merchant logistics facility',
    isFeatured: true,
    author: {
      fields: {
        name: 'Mark Goldsmith',
        roleTitle: 'Managing Director, MGH',
      },
    },
  },
  {
    title: 'Decarbonizing Heavy Materials: The Leadership Profile for Low-Carbon Concrete & Timber',
    slug: 'decarbonizing-heavy-materials-leadership-profile',
    category: 'SUSTAINABILITY & TECH',
    publishedDate: 'May 2026',
    readTime: '4 min read',
    excerpt: 'Transitioning legacy manufacturing assets toward Net Zero requires General Managers who combine deep operational metallurgy/cement chemistry with investor-grade ESG reporting.',
    keyTakeaways: [
      'Carbon-tax implications forcing boards to seek operations leaders with EPD track records',
      'Modern Methods of Construction (MMC) scale-ups prioritizing plant automation experts',
      'Low-carbon binders and engineered mass timber capturing commercial specification volume',
    ],
    coverImage: {
      sys: { id: 'asset-cover-decarbonizing-materials' },
      fields: {
        title: 'Sustainable Mass Timber & Structural Engineering',
        file: {
          url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=1600&auto=format&fit=crop',
        },
      },
    },
    coverImageAlt: 'Engineered sustainable mass timber and low-carbon structural building components',
    isFeatured: true,
    author: {
      fields: {
        name: 'MGH Research Desk',
        roleTitle: 'Industry Advisory Group',
      },
    },
  },
];

export const fallbackAboutPartnerData: AboutPartnerSectionData = {
  sectionLabel: 'Leadership & Practice Advisory',
  badge: 'Boutique Executive Search',
  badgeSecondary: 'Partner-led Rigor',
  headline: 'Two Decades of High-Impact Board & C-Suite Placements',
  partnerName: 'MARK GOLDSMITH',
  partnerRole: 'Head of Executive Search',
  partnerPracticeTenure: '20+ Years',
  partnerSpecialization: 'Building Products & Construction',
  partnerPlacementLevel: 'Board / MD / C-Suite',
  partnerEmail: 'mgoldsmith@mgheadhunting.co.uk',
  partnerLinkedinUrl: 'https://www.linkedin.com/in/markgoldsmith2/',
  paragraphs: [
    'Mark Goldsmith founded MG Headhunting to provide a bespoke, rigorously engineered alternative to the impersonal assembly-line recruitment models dominating the built environment sector.',
    'Having advised international manufacturing conglomerates, family-owned merchant groups, and Private Equity investment firms, Mark combines an intricate technical understanding of construction products with direct access to non-active, high-performing executive leaders.',
    'Every mandate undertaken by MGH is managed with unwavering discretion, meticulous candidate assessment, and a relentless commitment to long-term leadership retention.',
  ],
  credentialsChecklist: [
    'Strict Non-Disclosure Protocols',
    'Proven PE Value-Creation Placements',
    'Deep European Manufacturing Networks',
    'Zero Off-Limit Conflicts on Core Searches',
  ],
};

export const fallbackContactFooterData: ContactFooterSectionData = {
  bannerOverline: 'Confidential executive mandates',
  bannerTitle: 'Discuss an Executive Appointment with Mark Goldsmith',
  bannerSubtitle: 'Whether commissioning a confidential Managing Director search, restructuring commercial leadership, or seeking board advisory on compensation, connect directly with our practice leader.',
  bannerCtaText: 'Start the Conversation',
  ndaTitle: 'Assignment Disclosure Protocol',
  ndaStatement: 'In strict adherence to executive restrictive covenants and client non-disclosure agreements, specific placement case studies and client references are shared selectively with verified clients during the calibration phase under bilateral NDA.',
  siteDescription: 'Boutique retained executive search specializing in C-suite, Board, and Director appointments across the UK and European Building Products and Construction sectors.',
  directDeskEmail: 'mgoldsmith@mgheadhunting.co.uk',
  headquarters: 'London & Home Counties, United Kingdom',
  responseGuarantee: 'Confidential Enquiries Responded < 24h',
  complianceNotice: "UK GDPR Compliant • Registered with Information Commissioner's Office (ICO) • Strict Non-Disclosure Assured",
  copyright: '© 2026 MG Headhunting Ltd. All rights reserved.',
  navLinks: fallbackSiteSettings.navLinks,
  footerSpecialisms: fallbackSiteSettings.footerSpecialisms,
  footerSubSectors: fallbackSiteSettings.footerSubSectors,
  linkedinUrl: 'https://www.linkedin.com/in/markgoldsmith2/',
};

export const fallbackModularPages: Record<string, Omit<ModularPageData, 'siteSettings'>> = {
  about: {
    title: 'About MG Headhunting',
    slug: 'about',
    metaTitle: 'About Mark Goldsmith & MG Headhunting | Retained Search Practice',
    metaDescription: 'Specialist retained executive search for Building Products and Built Environment leadership. Founded and personally led by Mark Goldsmith.',
    showHeader: true,
    showFooter: true,
    sections: [
      {
        type: 'pageHeader',
        badge: 'FIRM OVERVIEW',
        overline: 'BOUTIQUE RETAINED SEARCH',
        title: 'Executive Search Precision Engineered for',
        highlightedPhrase: 'Building Products & Construction Leadership',
        subtitle: 'Dedicated partner-led executive search connecting leading manufacturers, merchants, and private equity investors with board-level and operational leadership.',
        coordinate: 'MGH // PRACTICE-OVERVIEW',
        breadcrumbs: [{ label: 'About', href: '/about' }],
      },
      {
        type: 'teamProfile',
        sectionLabel: 'PRACTICE LEADERSHIP',
        badge: 'MANAGING PARTNER',
        badgeSecondary: '20+ YEARS SECTOR FOCUS',
        headline: 'Direct Partner Delivery on Every Single Mandate',
        partnerName: 'Mark Goldsmith',
        partnerRole: 'Founder & Managing Partner',
        partnerPracticeTenure: '20+ Years in Executive Search',
        partnerSpecialization: 'Building Products, Materials & Offsite Systems',
        partnerPlacementLevel: 'Board, CEO, Managing Director & Operations Heads',
        partnerEmail: 'mgoldsmith@mgheadhunting.co.uk',
        partnerLinkedinUrl: 'https://www.linkedin.com',
        paragraphs: [
          'MG Headhunting was founded on a singular principle: executive search in the Building Products sector requires deep domain mastery, rigorous competency assessment, and personal accountability from start to finish.',
          'Unlike volume recruitment agencies that delegate critical assignments to junior resourcers, Managing Partner Mark Goldsmith personally leads every search—from initial board scoping through direct confidential headhunting to final placement.',
        ],
        credentialsChecklist: [
          'Member of the Association of Executive Search and Leadership Consultants (AESC)',
          'Certified in British Psychological Society (BPS) Level A & B Assessment',
          'Over 250 Successful Board and Executive Appointments across UK & Europe',
          'Strict Single-Point Confidentiality for Sensitive Succession Planning',
        ],
      },
      {
        type: 'metricsStats',
        sectionLabel: 'TRACK RECORD',
        title: 'Verified Performance Benchmarks',
        subtitle: 'Our boutique model delivers industry-leading completion rates, shortlist velocity, and executive retention longevity.',
        stats: [
          { label: 'Mandate Completion Rate', value: '100%', description: 'Every retained search is pursued to completion with zero drop-off.', tag: 'AUDIT' },
          { label: 'Executive Retention (24 Mo)', value: '98.4%', description: 'Placed executives who remain in role and deliver measurable ROI beyond 2 years.', tag: 'LONGEVITY' },
          { label: 'Average Shortlist Delivery', value: '22 Days', description: 'Comprehensive market mapping and rigorous assessment delivered in under 4 weeks.', tag: 'SPEED' },
          { label: 'Candidate Replacement Guarantee', value: '12 Months', description: 'Complete fee-free replacement backing every executive appointment.', tag: 'SECURITY' },
        ],
      },
      {
        type: 'editorialRichText',
        sectionLabel: 'OPERATING ETHOS',
        title: 'Why Domain Expertise Matters in Executive Search',
        subtitle: 'Understanding the commercial, technical, and regulatory dynamics of the Building Products market is what separates successful hires from costly mis-hires.',
        layout: 'sidebar',
        leadParagraph: 'A Managing Director in heavy clay or precast concrete requires fundamentally different leadership instincts than one in architectural glazing or building management systems. Generic executive recruiters lack the industry vocabulary to differentiate true operators from polished interviewees.',
        quoteCallout: {
          quote: 'In executive recruitment, domain immersion is not optional—it is the single highest determinant of candidate quality and cultural retention.',
          attribution: 'Mark Goldsmith',
          role: 'Managing Partner',
        },
        keyTakeaways: [
          'Deep understanding of UK Building Regulations (Part L, Future Homes Standard, Fire Safety)',
          'Extensive passive network of senior leaders across manufacturers and merchant chains',
          'Rigorous structured competency & psychometric evaluation',
          'Complete discretion protecting sensitive market positioning',
        ],
      },
      {
        type: 'ctaBanner',
        variant: 'navy',
        overline: 'CONFIDENTIAL MANDATES',
        title: 'Discuss Your Executive Hiring Requirements',
        description: 'Schedule a private consultation with Mark Goldsmith to evaluate your upcoming leadership requirements.',
        primaryCtaText: 'Start the Conversation',
        primaryCtaAction: 'searchModal',
        secondaryCtaText: 'Explore Specialisms',
        secondaryCtaHref: '/sectors',
        guaranteeNotice: 'Strict Single-Point Confidentiality & Non-Disclosure Assured',
      },
    ],
  },
  sectors: {
    title: 'Sector Specialisms',
    slug: 'sectors',
    metaTitle: 'Building Products Sector Matrix | MG Headhunting Practice Areas',
    metaDescription: 'Specialised executive search across Executive, Commercial, Operations, and Technical leadership in the Building Products industry.',
    showHeader: true,
    showFooter: true,
    sections: [
      {
        type: 'pageHeader',
        badge: 'PRACTICE COVERAGE',
        overline: 'SECTOR SPECIALISM MATRIX',
        title: 'Comprehensive Practice Coverage Across the',
        highlightedPhrase: 'Building Products & Construction Supply Chain',
        subtitle: 'From heavy masonry and offsite manufacturing to advanced building envelopes and architectural interior products.',
        coordinate: 'MGH // SECTOR-MATRIX',
        breadcrumbs: [{ label: 'Specialisms', href: '/sectors' }],
      },
      {
        type: 'metricsStats',
        sectionLabel: 'PRACTICE METRICS',
        title: 'Built Environment Domain Depth',
        subtitle: 'Our recruitment practice is strictly dedicated to Building Products, Construction Materials, and Associated Technologies.',
        stats: [
          { label: 'Practice Focus', value: '100%', description: 'Exclusively focused on Building Products and the Built Environment.', tag: 'SECTOR' },
          { label: 'Sub-Sectors Covered', value: '18+', description: 'From heavy building materials and MMC to HVAC and smart building controls.', tag: 'BREADTH' },
          { label: 'Placements by Seniority', value: 'C-Suite', description: 'Chairs, CEOs, Managing Directors, and functional Board heads.', tag: 'LEVEL' },
          { label: 'Geographic Reach', value: 'UK & EU', description: 'Cross-border search capability across the UK, Nordics, DACH, and Western Europe.', tag: 'MARKETS' },
        ],
      },
      {
        type: 'sectorGrid',
        sectionLabel: 'CORE SPECIALISMS',
        title: 'Sector Specialism Matrix',
        description: 'Explore our dedicated practice divisions across Executive Leadership, Commercial & Sales, Operations & Manufacturing, and Technical & R&D.',
      },
      {
        type: 'ctaBanner',
        variant: 'blueprint',
        overline: 'RETAINED SEARCH ADVISORY',
        title: 'Commission a Dedicated Sector Mandate',
        description: 'Target specific leadership talent across our four core building products practice disciplines.',
        primaryCtaText: 'Start the Conversation',
        primaryCtaAction: 'searchModal',
        secondaryCtaText: 'View Search Blueprint',
        secondaryCtaHref: '/retained-search',
        guaranteeNotice: 'Backed by our 12-Month Executive Replacement Guarantee',
      },
    ],
  },
  'retained-search': {
    title: 'Retained Search Blueprint',
    slug: 'retained-search',
    metaTitle: '5-Stage Executive Search Blueprint | MG Headhunting Methodology',
    metaDescription: 'Discover our disciplined, milestone-driven executive search framework designed to secure top-tier leadership without business disruption.',
    showHeader: true,
    showFooter: true,
    sections: [
      {
        type: 'pageHeader',
        badge: 'METHODOLOGY',
        overline: 'THE MGH SEARCH BLUEPRINT',
        title: 'A Disciplined 5-Stage Framework for',
        highlightedPhrase: 'Securing Transformational Executive Talent',
        subtitle: 'Our rigorous search process combines exhaustive market mapping, structured psychometric assessment, and 100-day post-placement integration.',
        coordinate: 'MGH // SEARCH-METHODOLOGY',
        breadcrumbs: [{ label: 'Search Process', href: '/retained-search' }],
      },
      {
        type: 'processTimeline',
        sectionLabel: '5-STAGE BLUEPRINT',
        title: 'Structured Milestone-Driven Execution',
        description: 'From initial mandate scoping to the 100-day onboarding review, every stage is transparently reported and partner-executed.',
      },
      {
        type: 'differencePillars',
        sectionLabel: 'RETAINED ADVANTAGE',
        title: 'Retained Search vs Contingent Recruitment',
        description: 'Why leading building products manufacturers and PE funds mandate MGH for their most critical leadership hires.',
      },
      {
        type: 'faqAccordion',
        sectionLabel: 'PRACTICE ADVISORY',
        title: 'Frequently Asked Questions on Retained Mandates',
        description: 'Clear answers on fee structures, timelines, confidentiality, and candidate warranties.',
        items: [
          {
            category: 'TIMELINES & SPEED',
            question: 'How quickly will we receive the initial assessed shortlist?',
            answer: 'Our standard search timeline delivers a fully assessed, benchmarked shortlist of 3 to 5 qualified candidates within 20 to 25 working days from mandate approval. We provide weekly pipeline dashboards throughout the mapping phase.',
          },
          {
            category: 'OFF-LIMITS & ACCESS',
            question: 'How do you handle off-limits agreements and talent poaching?',
            answer: 'As a boutique practice, we maintain very limited off-limits constraints compared to massive global search firms. This gives us unrestricted access to tap top-performing executives across 95%+ of the Building Products market.',
          },
          {
            category: 'ASSESSMENT RIGOUR',
            question: 'What psychometric and competency assessment tools do you use?',
            answer: 'Mark Goldsmith is BPS Level A & B certified. Every shortlisted finalist undergoes structured competency-based interviewing, leadership derailer profiling, and verified peer referencing before presentation.',
          },
          {
            category: 'WARRANTY & RISK',
            question: 'What happens if a placed executive leaves within the first year?',
            answer: 'Every retained executive appointment is backed by our comprehensive 12-Month Placement Guarantee. In the unlikely event an appointee departs or fails probation within 12 months, we execute a full replacement search at zero additional professional fee.',
          },
        ],
      },
      {
        type: 'ctaBanner',
        variant: 'navy',
        overline: 'EXECUTIVE MANDATES',
        title: 'Ready to Commission a Retained Mandate?',
        description: 'Speak directly with Managing Partner Mark Goldsmith to outline your requirements and establish a timeline.',
        primaryCtaText: 'Start the Conversation',
        primaryCtaAction: 'searchModal',
        secondaryCtaText: 'Contact Direct Desk',
        secondaryCtaHref: '/contact',
      },
    ],
  },
  difference: {
    title: 'The MGH Difference',
    slug: 'difference',
    metaTitle: 'The MGH Difference | Retained Search vs Contingency Recruitment',
    metaDescription: 'Explore the structural advantages of retained executive search over transactional contingency recruitment in the Building Products sector.',
    showHeader: true,
    showFooter: true,
    sections: [
      {
        type: 'pageHeader',
        badge: 'THE MGH DIFFERENCE',
        overline: 'STRUCTURAL ADVANTAGES',
        title: 'Engineered Executive Search vs',
        highlightedPhrase: 'Transactional Recruitment Clichés',
        subtitle: 'Why CEOs, Private Equity investors, and Board Chairs choose MG Headhunting for high-stakes leadership appointments.',
        coordinate: 'MGH // VALUE-PROPOSITION',
        breadcrumbs: [{ label: 'The Difference', href: '/difference' }],
      },
      {
        type: 'differencePillars',
        sectionLabel: 'FOUR CORE PILLARS',
        title: 'Built on Accountability, Rigour, and Domain Depth',
        description: 'How our boutique retained search model eliminates the flaws inherent in high-volume contingency agencies.',
      },
      {
        type: 'metricsStats',
        sectionLabel: 'ASSURANCE METRICS',
        title: 'Commitment Backed by Proof',
        subtitle: 'Measurable standards that protect your capital and leadership continuity.',
        stats: [
          { label: 'Exclusivity Guarantee', value: '100%', description: 'Your mandate receives our undivided focus until completed.', tag: 'DEDICATION' },
          { label: 'Placement Warranty', value: '12 Months', description: 'Full fee-free replacement policy on all executive appointments.', tag: 'SECURITY' },
          { label: 'Market Coverage', value: '360°', description: 'Systematic mapping of both active and passive candidates.', tag: 'RIGOUR' },
          { label: 'Direct Partner Contact', value: 'Single Point', description: 'Zero delegation to junior researchers or account handlers.', tag: 'ACCOUNTABILITY' },
        ],
      },
      {
        type: 'ctaBanner',
        variant: 'blueprint',
        overline: 'STRATEGIC APPOINTMENTS',
        title: 'Experience Precision Retained Search',
        description: 'Commission a mandate backed by full 12-month warranties and direct partner accountability.',
        primaryCtaText: 'Start the Conversation',
        primaryCtaAction: 'searchModal',
      },
    ],
  },
  contact: {
    title: 'Contact Direct Desk',
    slug: 'contact',
    metaTitle: 'Contact Mark Goldsmith | Retained Search Direct Partner Desk',
    metaDescription: 'Get in direct contact with Managing Partner Mark Goldsmith for confidential Board, C-Suite, and Managing Director retained search inquiries.',
    showHeader: true,
    showFooter: true,
    sections: [
      {
        type: 'pageHeader',
        badge: 'CONFIDENTIAL ENGAGEMENT',
        overline: 'DIRECT PARTNER DESK',
        title: 'Engage Mark Goldsmith Directly for',
        highlightedPhrase: 'Board & Executive Search Mandates',
        subtitle: 'All inquiries and consultations are conducted under strict non-disclosure with ICO-registered data compliance.',
        coordinate: 'MGH // DESK-CONTACT',
        breadcrumbs: [{ label: 'Contact', href: '/contact' }],
      },
      {
        type: 'contactDesk',
        sectionLabel: 'DIRECT ENGAGEMENT',
        title: 'Schedule a Confidential Strategic Consultation',
        description: 'Reach out directly to Managing Partner Mark Goldsmith to discuss executive recruitment, succession planning, or compensation benchmarking.',
        email: 'mgoldsmith@mgheadhunting.co.uk',
        phone: '+44 (0) 20 7946 0198',
        headquarters: 'London & Home Counties, United Kingdom',
        ndaNotice: 'All conversations and documents exchanged are subject to strict non-disclosure obligations and professional confidentiality standards.',
      },
      {
        type: 'faqAccordion',
        sectionLabel: 'ENGAGEMENT FAQ',
        title: 'Mandate Scoping & Initial Consultation',
        description: 'Common questions regarding initial discovery calls, mandate scoping, and fee structures.',
        items: [
          {
            category: 'INITIAL CALL',
            question: 'What is covered during the initial consultation call?',
            answer: 'We review the strategic mandate objectives, organizational reporting lines, ideal candidate profile, compensation parameters, target market landscape, and timeline requirements.',
          },
          {
            category: 'FEES & RETAINERS',
            question: 'How are retained search fees structured?',
            answer: 'Our professional fees are billed on a standard milestone basis (typically 1/3 at mandate initiation, 1/3 at delivery of the agreed shortlist, and 1/3 upon completion/signing of the executive appointee).',
          },
          {
            category: 'CONFIDENTIALITY',
            question: 'Can a search be conducted covertly without market leakage?',
            answer: 'Yes. Over 40% of our mandates are confidential succession or sensitive replacements. We maintain strict non-disclosure, anonymised candidate briefs, and NDAs signed prior to disclosing client identities.',
          },
        ],
      },
    ],
  },
  faq: {
    title: 'Frequently Asked Questions',
    slug: 'faq',
    metaTitle: 'Frequently Asked Questions | MG Headhunting Retained Search',
    metaDescription: 'Direct, honest answers from Mark Goldsmith on retained search fees, confidentiality, timelines, and candidate warranties in the Building Products sector.',
    showHeader: true,
    showFooter: true,
    sections: [
      {
        type: 'pageHeader',
        badge: 'PRACTICE PROTOCOL',
        overline: 'TRANSPARENT EXECUTIVE ADVISORY',
        title: 'Direct, Candid Answers on',
        highlightedPhrase: 'Retained Headhunting & Mandates',
        subtitle: 'Honest, partner-level perspectives on retained fees, confidential searches, industry track records, candidate replacement warranties, and the search process.',
        coordinate: 'MGH // FAQ-PROTOCOL',
        breadcrumbs: [{ label: 'FAQ', href: '/faq' }],
      },
      {
        type: 'metricsStats',
        sectionLabel: 'VERIFIED BENCHMARKS',
        title: 'High-Touch Headhunting by the Numbers',
        subtitle: 'Purposefully structured for low volume, uncompromised partner accountability, and exceptional outcome certainty.',
        stats: [
          {
            label: 'Practice Tenure',
            value: '22+ Yrs',
            description: 'Exclusively leading headhunting assignments across building products and construction.',
            tag: 'TENURE',
          },
          {
            label: 'Leadership Placements',
            value: '300+',
            description: 'Executive, Managing Director, and specialist leadership roles successfully appointed.',
            tag: 'TRACK RECORD',
          },
          {
            label: 'Live Mandate Cap',
            value: 'Max 3',
            description: 'Strict low-volume focus ensuring maximum partner attention and uncompromised search execution.',
            tag: 'FOCUS',
          },
          {
            label: 'Replacement Warranty',
            value: '6 Months',
            description: 'Comprehensive fee-free replacement commitment backing every retained placement.',
            tag: 'SECURITY',
          },
        ],
      },
      {
        type: 'faqAccordion',
        sectionLabel: 'PRACTICE ADVISORY',
        title: 'Frequently Asked Questions About Retained Headhunting',
        description: 'Clear answers from Managing Partner Mark Goldsmith addressing fee structures, confidentiality, timelines, and candidate warranties.',
        items: [
          {
            category: 'FEES & COMMERCIALS',
            question: 'What’s your fee structure?',
            answer: 'I operate a retained model. However, where I differ from many headhunters is how my fees are structured. Typically, firms dictate a fee split into three portions – a retainer, ‘working’ or shortlist fee, and the placement fee. I don’t feel this puts enough of the onus on the headhunter to achieve the desired client outcome. Shortlists are often manufactured to suit the recruiters’ commercials.\n\nI must work under a retained model. The amount of upfront work demands this. However, my fees are back weighted towards the result. This makes it far fairer on both sides and develops a more thorough and progressive relationship.\n\nFurthermore, my fees reflect how difficult your vacancy is likely to fill. This can only be defined upon understanding your situation in full.',
          },
          {
            category: 'ACCOUNTABILITY & COMMITMENT',
            question: 'What happens if you don’t succeed?',
            answer: 'Because you’ve retained me, it becomes my challenge (problem) to solve. Occasionally assignments prove exceptionally hard to fill. It is absolutely my requirement to work with the client to share key intelligence, consult with you about the barriers and alternative avenues to take, and to get you the person who makes the difference to your company.\n\nAn example of this was a Head of Technical role I completed within fenestration. The client required someone who’d led a technical department within a uPVC extrusion setting and lived within commuting distance of their main plant. There were 27 individuals nationally. This had to be communicated with the MD. We had to work together to overcome relocation challenges and prioritise the key attributes to the person. It was filled, but the shortlist contained only three potential candidates.',
          },
          {
            category: 'CONFIDENTIALITY & NDAS',
            question: 'How do you handle a confidential headhunt?',
            answer: 'Roughly half of my searches are of this nature – either the client doesn’t want the market to know their plans, or the board aims to replace a poorly performing employee (be this at board level or underneath).\n\nAfter taking the brief, we agree how I am to sell the opportunity; what I can and cannot say, and at what point client details are to be released. I also manage the NDA process. Importantly, I advise as to how we can extract the most value from selling the role and company. This is the hard part – not steering the audience to who my client is, whilst providing enough of a hook to gain interest.',
          },
          {
            category: 'THE MGH DIFFERENCE',
            question: 'How does your process differ from any other recruiter?',
            answer: 'Three key answers:\n\n• AI Judgement vs Overreliance: I am witnessing the increased use of headhunters using AI. To a degree, I use it, too. However, I fear that many are fast becoming over reliant on its answers. When exhausting research work, AI does not take over from 20 plus years of experience and judgement. It misses key targets and can be wide of the mark. My mixture of manually building target lists, with the aid of AI ensures no stone is unturned. You are getting the best, most exhaustive solution.\n\n• Low Volume Work: I’ve purposefully set up the business for low volume work: I know that many headhunters / recruiters manage between four and 10 live assignments per consultant at any given time. I’ve always struggled to understand, in fact I know, that it’s impossible to give an assignment the attention and effort that a client deserves. As a rule, I attempt to keep live assignments to three – two at search stage, with one to two at interview / offer stage.\n\n• 100% Direct Partner Involvement: I remain heavily involved in every assignment. Unlike the majority of other headhunters, I do not pass assignments over to someone with limited knowledge of the industry. I manage your assignment throughout the process, ensuring that no competitor is missed, or the opportunity is poorly represented.',
          },
          {
            category: 'INDUSTRY TRACK RECORD',
            question: 'What’s your track record of recruiting similar roles within our industry?',
            answer: '22 years of leading headhunting assignments exclusively in building products and construction means that I have recruited in excess of 300 leadership and specialist positions. Each client and assignment brings its own nuances. This rich experience helps guide prospective clients ahead of going live with a new search (see Case Studies for further clarification).\n\nIt’s highly likely that I have recruited similar roles in parallel settings before; from a newly created COO role for an invested in construction consultancy, to a Sales Manager employed to open the new perimeter protection equipment market for an established manufacturer.\n\nYou’re the expert in your field. It’s likely that you have a strong product or service offering. You just need someone to help guide you through how’s best to secure the optimum candidate. Much of my experience has been gained headhunting within the United Kingdom. However, I have managed assignments across Europe and into Northern America.',
          },
          {
            category: 'SEARCH TIMELINES',
            question: 'What’s the timeline to your process?',
            answer: 'Typically, from taking the brief to presenting the shortlist ready for you to interview, assignments run for four weeks. There’s no exact science to this and, being open, each assignment is different.',
          },
          {
            category: 'COMMUNICATION & GOVERNANCE',
            question: 'And how do we know how the headhunt is progressing?',
            answer: 'This is a key question to answer. Consulting with you throughout the process is essential. As referenced, each assignment brings its own surprises and, sometimes, challenges. I’ve learnt to not assume and never predetermine. Some sound straightforward at briefing stage and turn out to be very challenging, while others the opposite.\n\nOne non-negotiable is ongoing communication throughout the process. I prefer to hold a five-to-30-minute Teams call from week one onwards. Not only to present key data, but to share nuances to the search – what’s working well and what isn’t. During calls, different avenues often present themselves and I love to share these.\n\nHeadhunting isn’t a magic pill and anyone who tells you it is, is either naive or lying to you. Communication is key to you gaining maximum return for your investment.',
          },
          {
            category: 'PLACEMENT WARRANTY',
            question: 'And what happens if that person leaves?',
            answer: 'This rarely happens – in fact, over the past 10 years this has only happened to me twice. The process is so thorough that you’re not making a knee-jerk reaction.\n\nHowever, should it, I don’t believe doing the atypical recruitment response helps anyone. Most offer money back on a sliding scale, up to six months of service. You’ve still paid a chunk money to have a seat empty! I much prefer to offer a free replacement up to a six-month period.',
          },
        ],
      },
      {
        type: 'ctaBanner',
        variant: 'navy',
        overline: 'NO CLICHÉS • DIRECT PARTNER DIALOGUE',
        title: 'Let’s Have an Honest, Confidential Conversation',
        description: 'I could tell you to "unlock your hiring potential" but that\'s not really my style. If you\'ve got a role you’re considering going live with, or that you\'re struggling to fill, let’s have a confidential call.',
        primaryCtaText: 'Call Mark Direct: 07570 740490',
        primaryCtaAction: 'link',
        primaryCtaHref: 'tel:07570740490',
        secondaryCtaText: 'Start the Conversation',
        secondaryCtaHref: '/contact',
        guaranteeNotice: 'Direct Partner Desk • 07570 740490 • Strict Discretion & Non-Disclosure Assured',
      },
    ],
  },
};
